### ISSUE TITLE
Only the first message is exported for non-English exports

### ISSUE THREAD

**Issue by ShadyMedic** [AymaneHrouch/WhatsappBackupReader#1]
The best WhatsApp export parser I've seen so far, but for some reason, it only exports the first message from my exports.

My exports are in my native language and we use a different date format here, so maybe it's the problem?

This is my export file:
```
15.01.21 11:13 - Zprávy a hovory jsou zabezpečeny koncovým šifrováním. Nikdo, kdo není přímým účastníkem této konverzace, ji nemůže sledovat ani poslouchat. Dokonce ani WhatsApp. Další informace zobrazíte klepnutím.
15.01.21 11:13 - Vytvořil/a jste skupinu Debug whatsapp export API.
15.01.21 11:14 - User1: Ignoruj tohle
15.01.21 11:14 - User2: ?
15.01.21 11:14 - User1: Opusť tuhle skupinu pls.
15.01.21 11:14 - User2: Ok
15.01.21 11:15 - ‎User2 opustil/a skupinu.
15.01.21 11:15 - User1: Tuto zprávu jste odstranil/a.
15.01.21 11:16 - User1: ‎IMG-20210115-WA0000.jpg (soubor byl přiložen)
```

And this is how the output looks like:

![image](https://user-images.githubusercontent.com/19894267/104893464-c1a72580-5973-11eb-860b-1b6b3282f72d.png)

By the way, the string `(soubor byl přiložen)` is the equivalent of `(file attached)`. So if you use it to decide if you should display a media output, it might cause some problems as well.

**Comment by AymaneHrouch** [comment]
Hello @HonzaSTECH, thank you for reaching out.
Yes indeed, the language is the issue, this tool will only work with English, maybe in the future I may try to include other languages, if you still have the discussions change your phone's language to do the backup and then you can turn it back.

**Comment by AymaneHrouch** [comment]
This issue is fixed thanks to the contribution of @HonzaSTECH, now users with a different language than English can use it by setting the date format and the equivalent of "file attached" in their language.
